
total_value_of_business_case: str = "total-value-of-business-case"
part_of_wider_programme_with_existing_fbc: str = "part-of-wider-programme-with-existing-fbc"
request_part_of_wider_programme: str = "request-part-of-wider-programme"
does_request_involve_anything_digital: str = "does-request-involve-anything-digital"
is_this_request_a_pilot_with_potential_to_be_a_larger_proposal: str = "is-this-request-a-pilot-with-potential-to-be-larger"
novel_repercussive_contentious_hmt_consent: str = "novel-repercussive-contentious-hmt-consent"
is_this_request_part_of_a_wider_programme_with_existing_business_case: str = "is-this-request-part-of-a-wider-programme-with-existing-business-case"
any_other_business_cases_that_are_connected_to_this_work: str = "any-other-business-cases-that-are-connected-to-this-work"
where_is_the_budget_held: str = "where-is-the-budget-held"
is_this_a_retrospective_case: str ="is-this-a-retrospective-case"
which_option_describes_what_you_are_trying_to_do: str = "which-option-describes-what-you-are-trying-to-do"
commission_research: str = "commission-research"
procure_goods_and_services_from_third_party: str = "procure-goods-and-services-from-third-party"
hire_contracted_workers_to_fill_temporary_capacity_gap: str = "hire-contracted-workers-to-fill-temporary-capacity-gap"
which_best_describes_your_situation: str = "which-best-describes-your-situation"
spend_on_corporate_activities: str = "spend-on-corporate-activities"
procuring_something_else: str = "procuring-something-else"
give_your_bjc_a_name: str = "give-your-bjc-a-name"
procuring_something_else: str = "procuring-something-else"
are_you_procuring_consulting_and_professional_services: str = "are-you-procuring-consulting-and-professional-services"
we_want_to_continue_improving_our_service: str = "we-want-to-continue-mproving-our-service"
provide_a_high_level_summary: str = "provide-a-high-level-summary"
you_need_to_start_a_business_justification_case: str = "you-need-to-start-a-business-justification-case"

