services:
  web:
    environment:
      ENTRA_ID_ENABLED: "True"
      ENTRA_CLIENT_ID: "<client-id>"
      ENTRA_CLIENT_SECRET: "<client-secret>"
      ENTRA_AUTHORITY: "https://login.microsoftonline.com/organizations"
      ENTRA_REDIRECT_URI: "http://localhost:8080/accounts/auth_callback/"
      ENTRA_LOGOUT_REDIRECT: "http://localhost:8080/accounts/login/"
      ENTRA_ALLOWED_TENANTS: "<tenant-id>"
