[tool.poetry]
name = "business-case-improvements"
version = "0.1.0"
description = "MHCLG Business Case Improvement Tool"
authors = []
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
django = "^6.0"
jinja2 = "^3.1"
markupsafe = "^3.0"
whitenoise = "^6.7"
gunicorn = "^26.0"
python-dotenv = "^1.0"
govuk-frontend-jinja = "^4.0.0"
psycopg = {extras = ["binary"], version = "^3.3.4"}

[tool.poetry.group.dev.dependencies]
ruff = "^0.15"
pytest = "^9.0"
pytest-django = "^4.8"
django-debug-toolbar = "^6.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
target-version = "py312"
line-length = 88

[tool.ruff.lint]
select = ["E", "F", "I", "N", "W", "UP", "B", "SIM", "RUF", "DJ"]
ignore = ["E501", "RUF012", "DJ012", "RUF005"]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "config.settings"
testpaths = ["tests"]
pythonpath = ["."]