# Generated by Django 6.0.6 on 2026-07-16 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TriageSession',
            new_name='BusinessCaseTriageResponse',
        ),
        migrations.CreateModel(
            name='BusinessCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('business_case_triage_response', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='business_cases', to='triage.businesscasetriageresponse')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
