# Generated by Django 6.0.6 on 2026-08-19 08:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0002_businesscase'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscase',
            name='directorate',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='businesscase',
            name='lead_contact',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='businesscase',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='businesscase',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Uploaded', 'Uploaded'), ('Withdrawn', 'Withdrawn')], default='Active'),
        ),
        migrations.AddField(
            model_name='businesscase',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='businesscase',
            name='type',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='BusinessCaseResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('uploaded_by', models.CharField(default='-', max_length=150)),
                ('status', models.TextField(choices=[('Completed', 'Completed')], default='Completed')),
                ('business_case_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='triage.businesscase')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessCaseResponseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_text', models.CharField(default='', max_length=100)),
                ('business_case_response_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='triage.businesscaseresponse')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessCaseResponseBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.TextField(choices=[('Paragraph', 'Paragraph'), ('Table', 'Table')], default='Paragraph', help_text='The type of Block this data represents, e.g Paragraph, Table, etc.')),
                ('block_number', models.IntegerField(default=0, help_text='The order in which this block appeared under the header')),
                ('block_data', models.BinaryField()),
                ('business_case_response_section_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='triage.businesscaseresponsesection')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessCaseResponseSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_text', models.TextField()),
                ('whole_of_life_cost', models.CharField(default='0')),
                ('directorate', models.CharField(default='-')),
                ('sro_scs', models.CharField(default='-')),
                ('approved_by_sro_scs', models.DateField(default=django.utils.timezone.now)),
                ('author', models.CharField(default='-')),
                ('business_case_response_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='triage.businesscaseresponse')),
            ],
        ),
    ]
