# Generated by Django 6.0.6 on 2026-08-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0003_businesscase_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscase',
            name='directorate',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='businesscase',
            name='lead_contact',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='businesscase',
            name='status',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='businesscase',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='businesscase',
            name='type',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
