# Generated by Django 6.0.6 on 2026-08-19 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0003_businesscase_directorate_businesscase_lead_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesscase',
            name='directorate',
        ),
        migrations.RemoveField(
            model_name='businesscase',
            name='lead_contact',
        ),
        migrations.RemoveField(
            model_name='businesscase',
            name='name',
        ),
        migrations.RemoveField(
            model_name='businesscase',
            name='status',
        ),
        migrations.RemoveField(
            model_name='businesscase',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='businesscase',
            name='type',
        ),
    ]
